import Link from "next/link";
import { activeCategories, catalog } from "@/domains/commerce/commerce-service";
import { CatalogCards } from "@/components/catalog-cards";
import { pageNumber } from "@/db/queries/community";
export default async function MarketplacePage({ searchParams }: { searchParams: Promise<{ q?: string; categoryId?: string; sort?: string; page?: string }> }) {
  const search = await searchParams; const page = pageNumber(search.page);
  const categories = await activeCategories();
  const categoryId = categories.find(category => category.id === search.categoryId)?.id;
  const rows = await catalog({ query: search.q, categoryId, sort: search.sort, page });
  return <div className="site-container space-y-6 py-8"><div className="flex flex-wrap justify-between gap-4"><h1 className="text-display-sm">Marketplace</h1><Link className="button-secondary" href="/seller">Seller workspace</Link></div><form className="surface grid gap-3 p-4 sm:grid-cols-4"><label>Search<input className="field mt-2" name="q" defaultValue={search.q} maxLength={200} /></label><label>Category<select className="field mt-2" name="categoryId" defaultValue={categoryId ?? ""}><option value="">All categories</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Sort<select className="field mt-2" name="sort" defaultValue={search.sort ?? "newest"}><option value="newest">Newest</option><option value="price">Lowest price</option></select></label><button className="button-primary self-end">Apply filters</button></form>{categories.length > 0 && <nav aria-label="Marketplace categories" className="flex flex-wrap gap-3">{categories.map(category => <Link className="button-secondary" href={`/marketplace/categories/${category.slug}`} key={category.id}>{category.name}</Link>)}</nav>}<CatalogCards rows={rows} /><nav aria-label="Catalog pagination" className="flex gap-4">{page > 1 && <Link href={`?${new URLSearchParams({ q: search.q ?? "", categoryId: categoryId ?? "", sort: search.sort ?? "newest", page: String(page - 1) })}`}>Previous</Link>}{rows.length === 24 && <Link href={`?${new URLSearchParams({ q: search.q ?? "", categoryId: categoryId ?? "", sort: search.sort ?? "newest", page: String(page + 1) })}`}>Next</Link>}</nav></div>;
}
