import Link from "next/link";
import { activeCategories, catalog } from "@/domains/commerce/commerce-service";
import { CatalogCards } from "@/components/catalog-cards";
import { pageNumber } from "@/db/queries/community";
export default async function MarketplacePage({ searchParams }: { searchParams: Promise<{ q?: string; kind?: string; sort?: string; page?: string }> }) {
  const search = await searchParams; const page = pageNumber(search.page);
  const [rows, categories] = await Promise.all([catalog({ query: search.q, kind: search.kind, sort: search.sort, page }), activeCategories()]);
  return <div className="site-container space-y-6 py-8"><div className="flex flex-wrap justify-between gap-4"><h1 className="text-display-sm font-bold">Marketplace</h1><Link className="button-secondary" href="/seller">Seller workspace</Link></div><p className="text-text-muted">Digital goods and services from members. Review listings and contact sellers; payments and funded delivery are not available yet.</p><form className="surface grid gap-3 p-4 sm:grid-cols-4"><label>Search<input className="field mt-2" name="q" defaultValue={search.q} maxLength={200} /></label><label>Product kind<select className="field mt-2" name="kind" defaultValue={search.kind ?? ""}><option value="">All kinds</option><option value="digital">Digital goods</option><option value="service">Services</option></select></label><label>Sort<select className="field mt-2" name="sort" defaultValue={search.sort ?? "newest"}><option value="newest">Newest</option><option value="price">Lowest price</option></select></label><button className="button-primary self-end">Apply filters</button></form>{categories.length > 0 && <nav aria-label="Marketplace categories" className="flex flex-wrap gap-3">{categories.map(category => <Link className="button-secondary" href={`/marketplace/categories/${category.slug}`} key={category.id}>{category.name}</Link>)}</nav>}<CatalogCards rows={rows} /><nav aria-label="Catalog pagination" className="flex gap-4">{page > 1 && <Link href={`?${new URLSearchParams({ q: search.q ?? "", kind: search.kind ?? "", sort: search.sort ?? "newest", page: String(page - 1) })}`}>Previous</Link>}{rows.length === 24 && <Link href={`?${new URLSearchParams({ q: search.q ?? "", kind: search.kind ?? "", sort: search.sort ?? "newest", page: String(page + 1) })}`}>Next</Link>}</nav></div>;
}
