import Link from "next/link";
import { checkoutReview } from "@/domains/commerce/commerce-service";
import { formatUsd } from "@/domains/commerce/validation";
import { newPurchasesEnabled } from "@/domains/finance/gate";
import { CheckoutQuoteButton } from "./checkout-payment";
import { SelectionButton } from "./commerce-forms";
export async function CheckoutSummary({ listingId, cart = false, selectedCartIds }: { listingId?: string; cart?: boolean; selectedCartIds?: string[] }) {
  const items = await checkoutReview(listingId, selectedCartIds);
  if (!items.length) return <section className="surface space-y-3 p-6"><p>Your cart is empty.</p><Link className="text-category" href="/marketplace">Browse marketplace</Link></section>;
  const sellers = [...new Set(items.map(item => item.username))];
  const total = items.reduce((sum, item) => sum + (item.available && item.listing ? item.listing.priceCents : 0), 0);
  return <div className="space-y-5">{sellers.map(username => <section key={username ?? "unavailable"} className="surface space-y-4 p-6"><h2 className="text-heading-lg">{username ? `Seller: ${username}` : "Unavailable items"}</h2>{items.filter(item => item.username === username).map(item => <article key={item.id} className="space-y-3 border-t border-border pt-4">{cart && item.available && <label className="flex gap-3"><input form="cart-checkout" type="checkbox" name="item" value={item.id} defaultChecked />Include in checkout review</label>}{item.listing ? <><Link className="font-semibold text-category" href={`/marketplace/${item.id}/${item.listing.slug}`}>{item.listing.title}</Link><p>{formatUsd(item.listing.priceCents)} · {item.listing.fulfillmentMode} delivery · Quantity 1</p><p>{item.available ? "Available" : "Currently unavailable"}</p>{item.changed && <p role="status" className="text-yellow">The price changed since this item was added. This review shows the current price.</p>}<p className="whitespace-pre-wrap text-body-sm">{item.listing.deliveryTerms}</p><Link className="button-secondary" href={`/messages?to=${encodeURIComponent(item.username ?? "")}`}>Contact seller</Link></> : <p>This listing is no longer available. It remains in your cart until you remove it.</p>}{cart && <SelectionButton id={item.id} operation="cart.remove">Remove from cart</SelectionButton>}</article>)}</section>)}<section className="surface space-y-3 p-6"><p className="text-heading-lg">Available-item total: {formatUsd(total)}</p>{items.some(item => !item.available) && <p>Unavailable items are excluded from the total.</p>}{newPurchasesEnabled && !cart ? <CheckoutQuoteButton key={items.filter(item => item.available).map(item => item.id).sort().join(":")} listingIds={items.filter(item => item.available).map(item => item.id)} fromCart={!listingId} /> : <p>Reviewing creates no order or charge. {newPurchasesEnabled ? "Review selected items to request the exact USDT charge." : "Payments are not activated."}</p>}{cart && <form id="cart-checkout" action="/checkout"><input type="hidden" name="fromCart" value="1" /><button className="button-primary">Review selected items</button></form>}</section></div>;
}
