"use client";
import { useActionState } from "react";
import { listingAction, selectionAction, sellerAction } from "@/app/(product)/marketplace/actions";
export function SellerForm({ name = "", description = "" }: { name?: string; description?: string }) {
  const [state, action, pending] = useActionState(sellerAction, { message: "" });
  return <form action={action} className="surface space-y-4 p-6"><label className="block">Storefront name<input className="field mt-2" name="name" defaultValue={name} minLength={2} maxLength={80} required /></label><label className="block">Storefront description<textarea className="field mt-2 min-h-32" name="description" defaultValue={description} minLength={20} maxLength={5000} required /></label><p className="text-body-sm text-text-muted">Sell only digital goods or services you have the right to provide. Describe delivery and limitations accurately. Do not post protected deliverables in public listing descriptions. Payments, funded delivery and settlement are unavailable in this release.</p><label className="flex gap-3"><input type="checkbox" name="acceptedPolicy" required />I accept these seller policies (2026-09-pre-funding-v1).</label><button className="button-primary" disabled={pending}>Save storefront</button><p role="status">{state.message}</p></form>;
}
type ListingValues = { id: string; version: number; title: string; description: string; categoryId: string | null; kind: string; fulfillmentMode: string; deliveryTerms: string; priceCents: number; available: boolean; status: string };
export function ListingForm({ listing, categories }: { listing?: ListingValues; categories: Array<{ id: string; name: string }> }) {
  const [state, action, pending] = useActionState(listingAction, { message: "" });
  return <form action={action} className="surface space-y-5 p-6">{listing && <><input type="hidden" name="id" value={listing.id} /><input type="hidden" name="version" value={listing.version} /></>}<label className="block">Title<input className="field mt-2" name="title" defaultValue={listing?.title} minLength={5} maxLength={160} required /></label><label className="block">Description visible to members<textarea className="field mt-2 min-h-40" name="description" defaultValue={listing?.description} minLength={20} maxLength={20000} required /></label><label className="block">Product kind<select className="field mt-2" name="kind" defaultValue={listing?.kind ?? "digital"}><option value="digital">Digital goods</option><option value="service">Service</option></select></label><label className="block">Category<select className="field mt-2" name="categoryId" defaultValue={listing?.categoryId ?? ""}><option value="">No category</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="block">Price in USD<input className="field mt-2" name="price" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" defaultValue={listing ? (listing.priceCents / 100).toFixed(2) : ""} required /></label><label className="block">Delivery method<select className="field mt-2" name="fulfillmentMode" defaultValue={listing?.fulfillmentMode ?? "manual"}><option value="manual">Manual delivery</option><option value="text">Protected text</option><option value="file">Secure file (draft until approved file is attached)</option></select></label><label className="block">Delivery terms visible to members<textarea className="field mt-2" name="deliveryTerms" defaultValue={listing?.deliveryTerms} minLength={10} maxLength={5000} required /></label><label className="block">Protected text payload<textarea className="field mt-2 min-h-32" name="protectedText" maxLength={100000} aria-describedby="protected-help" /></label><p id="protected-help" className="text-body-sm text-text-muted">Encrypted on the server and never included in catalog or checkout. On an existing protected-text listing, leave blank to retain its saved payload. Buyer access remains blocked until verified payment is available.</p><label className="flex gap-3"><input type="checkbox" name="available" defaultChecked={listing?.available ?? true} />Available (unlimited; no inventory reservation)</label><label className="block">Publication status<select className="field mt-2" name="status" defaultValue={listing?.status ?? "draft"}><option value="draft">Draft</option><option value="published">Published</option><option value="paused">Paused</option><option value="archived">Archived</option></select></label><p role="status">{state.message}</p><button className="button-primary" disabled={pending}>Save listing revision</button></form>;
}
export function SelectionButton({ id, operation, children }: { id: string; operation: "cart.add" | "cart.remove" | "favorite.add" | "favorite.remove"; children: React.ReactNode }) {
  const [state, action, pending] = useActionState(selectionAction, { message: "" });
  return <form action={action} className="space-y-2"><input type="hidden" name="id" value={id} /><input type="hidden" name="operation" value={operation} /><button className="button-secondary" disabled={pending}>{children}</button><p role="status" className="text-body-sm">{state.message}</p></form>;
}
