"use client";
import { useActionState } from "react";
import { dealAction, draftAction } from "@/app/(product)/escrow/actions";
export function DealDraftForm({ draft }: { draft?: { id: string; version: number; name: string; respondent: string; payer: string; amountCents: number; terms: string } }) {
  const [state, action, pending] = useActionState(draftAction, { message: "" });
  return <form action={action} className="surface space-y-4 p-6">{draft && <><input type="hidden" name="id" value={draft.id} /><input type="hidden" name="version" value={draft.version} /></>}<label className="block">Agreement name<input className="field mt-2" name="name" defaultValue={draft?.name} minLength={3} maxLength={160} required /></label><label className="block">Respondent username<input className="field mt-2" name="respondent" defaultValue={draft?.respondent} minLength={3} maxLength={30} required /></label><label className="block">Who pays?<select className="field mt-2" name="payer" defaultValue={draft?.payer ?? "creator"}><option value="creator">I pay the respondent</option><option value="respondent">The respondent pays me</option></select></label><label className="block">USD amount<input className="field mt-2" name="amount" inputMode="decimal" defaultValue={draft ? (draft.amountCents / 100).toFixed(2) : ""} required /></label><label className="block">Complete agreement terms<textarea className="field mt-2 min-h-48" name="terms" defaultValue={draft?.terms} minLength={20} maxLength={20000} required /></label><p>Saving creates an editable draft. Sending freezes these terms and records your consent. Acceptance stops at AWAITING_FUNDING; no money is held or transferred.</p><button className="button-primary" disabled={pending}>Save draft</button><p role="status">{state.message}</p></form>;
}
export function DealTransitionForm({ id, version, operationId, actions }: { id: string; version: number; operationId: string; actions: Array<"invite" | "accept" | "decline" | "cancel"> }) {
  const [state, action, pending] = useActionState(dealAction, { message: "" });
  const labels = { invite: "Agree to terms and send invitation", accept: "Accept these exact terms", decline: "Decline invitation", cancel: "Cancel unfunded agreement" };
  return <form action={action} className="space-y-3"><input type="hidden" name="id" value={id} /><input type="hidden" name="version" value={version} /><input type="hidden" name="operationId" value={operationId} /><div className="flex flex-wrap gap-3">{actions.map(operation => <button className="button-secondary" key={operation} name="action" value={operation} disabled={pending}>{labels[operation]}</button>)}</div><p role="status">{state.message}</p></form>;
}
