"use client";
import { useActionState } from "react";
import { forumAction } from "@/app/(product)/threads/actions";
export function ForumControls({ threadId, subscribed, moderator, locked, pinned }: { threadId: number; subscribed: boolean; moderator: boolean; locked: boolean; pinned: boolean }) {
  const [state, action, pending] = useActionState(forumAction, { message: "" });
  return <section className="surface space-y-4 p-5" aria-label="Thread controls"><form action={action}><input type="hidden" name="threadId" value={threadId} /><button className="button-secondary" name="operation" value={subscribed ? "unsubscribe" : "subscribe"} disabled={pending}>{subscribed ? "Unsubscribe" : "Subscribe to replies"}</button></form><details><summary className="cursor-pointer">Report{moderator ? " or moderate" : ""} this thread</summary><form action={action} className="mt-3 space-y-3"><input type="hidden" name="threadId" value={threadId} /><label className="block">Reason<textarea className="field mt-2" name="reason" required minLength={5} maxLength={2000} /></label><div className="flex flex-wrap gap-3"><button name="operation" value="report" className="button-secondary" disabled={pending}>Submit report</button>{moderator && <><button name="operation" value={locked ? "unlock" : "lock"} className="button-secondary" disabled={pending}>{locked ? "Unlock" : "Lock"}</button><button name="operation" value={pinned ? "unpin" : "pin"} className="button-secondary" disabled={pending}>{pinned ? "Unpin" : "Pin"}</button></>}</div></form></details><p role="status">{state.message}</p></section>;
}
export function PostControls({ threadId, postId, text, updatedAt, canEdit }: { threadId: number; postId: number; text: string; updatedAt: string; canEdit: boolean }) {
  const [state, action, pending] = useActionState(forumAction, { message: "" });
  return <details className="border-t border-border pt-4"><summary className="cursor-pointer text-body-sm">{canEdit ? "Edit, delete or report post" : "Report post"}</summary><form action={action} className="mt-3 space-y-3"><input type="hidden" name="threadId" value={threadId} /><input type="hidden" name="postId" value={postId} /><input type="hidden" name="expectedUpdatedAt" value={updatedAt} />{canEdit && <label className="block text-body-sm">Post text<textarea className="field mt-2 min-h-32" name="text" defaultValue={text} maxLength={20000} /></label>}<label className="block text-body-sm">Reason<textarea className="field mt-2" name="reason" required minLength={5} maxLength={2000} /></label><div className="flex flex-wrap gap-3">{canEdit && <><button className="button-secondary" name="operation" value="edit" disabled={pending}>Save edit</button><button className="button-secondary" name="operation" value="delete" disabled={pending}>Soft-delete post</button><a className="button-secondary" href={`/threads/posts/${postId}/history`}>Edit history</a></>}<button className="button-secondary" name="operation" value="report" disabled={pending}>Report</button></div><p role="status">{state.message}</p></form></details>;
}
